version: "3"
services:
  web-app:
    build:
      context: ./web_app
      dockerfile: Dockerfile
    image: angstisdocker/webapp:latest
    container_name: web-app-container
    ports:
      - "5001:5000"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: angstisdocker/client:latest
    container_name: client-container
    ports:
      - "5002:5002"
  database:
    image: mongo:4.0-xenial
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: